### ISSUE TITLE
Define way of sending data between arm arduino and direct_motor_control node

### ISSUE THREAD

**Issue by newmanjoel** [Uvic-Robotics-Club/RoverArm#2]

**Comment by newmanjoel** [comment]
Needs review so that we can confirm that this is the best way of controlling the rover.

**Comment by newmanjoel** [comment]
This is the ROS to serial interface. This needs to be implemented on a arduino and test the protocol.

**Comment by lamwx** [comment]
While running the direct_motor_control node I can publish to /Arm/Position and receive the information on the arduino. The stepper motor for base rotation is working. I had to edit the serial protocol slightly to get it working on my machine. I'll send a pull with the changes shortly.

**Comment by newmanjoel** [comment]
Awesome, thanks dude. I look forward to it.
